#!/usr/bin/env python3
"""Build Metricool batch-import CSV files from calendar.json.

Reads   x/calendar.json
Writes  x/metricool-template-part1.csv  (first 28 posts in time order)
        x/metricool-template-part2.csv  (remaining posts)
        x/metricool-threads.md          (threads and first replies, added by hand)

The column list follows Metricool's own CSV template as documented on
help.metricool.com ("How to schedule posts in batch with a CSV file in
Metricool", read 9 October 2026). Every post is imported as a draft for X only.
Times are converted from UTC to the brand timezone (assumption: America/Santo_Domingo).
No network access; nothing is posted.
"""
import csv
import json
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

HERE = Path(__file__).resolve().parent
CALENDAR = HERE / "calendar.json"
PART1 = HERE / "metricool-template-part1.csv"
PART2 = HERE / "metricool-template-part2.csv"
THREADS = HERE / "metricool-threads.md"

BRAND_TZ = ZoneInfo("America/Santo_Domingo")
PART1_SIZE = 28

NETWORKS = ["Facebook", "Twitter/X", "LinkedIn", "GBP", "Instagram", "Pinterest",
            "TikTok", "YouTube", "Threads", "Bluesky"]

COLUMNS = (
    ["Text", "Date", "Time", "Draft"]
    + NETWORKS
    + [f"Picture Url {i}" for i in range(1, 11)]
    + [f"Alt text picture {i}" for i in range(1, 11)]
    + ["Document title", "Shortener", "Video Thumbnail Url", "Video Cover Frame",
       "Twitter/X Can reply", "Twitter/X Type", "Twitter/X Poll Duration minutes"]
    + [f"Twitter/X Poll Option {i}" for i in range(1, 5)]
    + ["Pinterest Board", "Pinterest Pin Title", "Pinterest Pin Link",
       "Pinterest Pin New Format", "Instagram Post Type", "Instagram Show Reel On Feed",
       "YouTube Video Title", "YouTube Video Type", "YouTube Video Privacy",
       "YouTube video for kids", "YouTube Video Category", "YouTube Video Tags",
       "YouTube Playlist", "YouTube Notify Subscribers", "GBP Post Type",
       "Facebook Post Type", "Facebook Title", "First Comment Text", "TikTok Title",
       "TikTok disable comments", "TikTok disable duet", "TikTok disable stitch",
       "TikTok Post Privacy (personal accounts only)",
       "TikTok Branded Content (personal accounts only)",
       "TikTok Your Brand (personal accounts only)",
       "TikTok Auto Add Music (personal accounts only)",
       "TikTok Photo Cover Index", "TikTok musicId", "TikTok music title",
       "TikTok music author", "TikTok music previewUrl", "TikTok music thumbnailUrl",
       "TikTok music soundVolume", "TikTok music originalVolume",
       "TikTok music startMillis", "TikTok music endMillis", "LinkedIn Type",
       "LinkedIn Poll Question"]
    + [f"LinkedIn Poll Option {i}" for i in range(1, 5)]
    + ["LinkedIn Poll Duration", "LinkedIn Show link preview",
       "LinkedIn Images as Carousel", "Threads Reply Control", "Threads Is Spoiler",
       "Threads Post Type", "Brand name (Optional)"]
)


def parse_utc(when):
    return datetime.fromisoformat(when.replace("Z", "+00:00"))


def local(when):
    return parse_utc(when).astimezone(BRAND_TZ)


def row_for(post):
    loc = local(post["when"])
    values = {c: "" for c in COLUMNS}
    values["Text"] = post["text"]
    values["Date"] = loc.strftime("%Y-%m-%d")
    values["Time"] = loc.strftime("%H:%M:%S")
    values["Draft"] = "TRUE"
    for net in NETWORKS:
        values[net] = "FALSE"
    values["Twitter/X"] = "TRUE"
    media = post.get("media") or []
    if media:
        values["Picture Url 1"] = media[0]
    values["Shortener"] = "FALSE"
    if post.get("reply"):
        values["First Comment Text"] = post["reply"]
    return [values[c] for c in COLUMNS]


def write_csv(path, posts):
    with open(path, "w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(COLUMNS)
        for post in posts:
            writer.writerow(row_for(post))


def write_threads(path, posts):
    threaded = [p for p in posts if p.get("thread")]
    lines = [
        "# X threads to add by hand in the Metricool planner",
        "",
        "Generated by make_metricool_csv.py from calendar.json. The CSV import carries only the",
        "opening post (as a draft) and its first reply in First Comment Text; the follow-up",
        "posts below are added by hand as a thread in the planner.",
        "Local times are America/Santo_Domingo (assumed brand timezone).",
        "",
        f"Threads: {len(threaded)}",
        "",
    ]
    for p in threaded:
        loc = local(p["when"])
        utc = parse_utc(p["when"])
        lines += [
            f"## {p['id']}: {loc:%Y-%m-%d %H:%M} local ({utc:%Y-%m-%d %H:%M} UTC)",
            "",
            "Opening post:",
            "",
            p["text"],
            "",
            "Follow-up posts:",
            "",
        ]
        for i, t in enumerate(p["thread"], 1):
            lines += [f"{i}. {t}", ""]
        lines += ["First reply:", "", p.get("reply") or "(none)", "", "---", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return len(threaded)


def main():
    data = json.loads(CALENDAR.read_text(encoding="utf-8"))
    posts = sorted(data["posts"], key=lambda p: parse_utc(p["when"]))
    part1, part2 = posts[:PART1_SIZE], posts[PART1_SIZE:]
    write_csv(PART1, part1)
    write_csv(PART2, part2)
    n_threads = write_threads(THREADS, posts)
    print(f"{PART1.name}: {len(part1)} rows")
    print(f"{PART2.name}: {len(part2)} rows")
    print(f"columns: {len(COLUMNS)}")
    print(f"{THREADS.name}: {n_threads} threads")


if __name__ == "__main__":
    main()
